const BREAKPOINTS = ["sm", "md", "lg", "xl"];
const SM_BREAKPOINT = 640;
const MD_BREAKPOINT = 768;
const LG_BREAKPOINT = 1024;
const XL_BREAKPOINT = 1280;

exports.SM_BREAKPOINT = SM_BREAKPOINT
exports.MD_BREAKPOINT = MD_BREAKPOINT
exports.LG_BREAKPOINT = LG_BREAKPOINT
exports.XL_BREAKPOINT = XL_BREAKPOINT
